[package]
name = "combat"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bevy = "0.18"
models = { path = "../models" }
derive_more = { version = "2.1.1", features = ["full"] }
